foreground = yes
pid =
client = yes

[mqtts]
accept = 127.0.0.1:18883
connect = your-mqtts-broker.example.com:8883
CAfile = /opt/modbus-gateway/config/runtime/tls/ca.crt
verifyChain = yes
checkHost = your-mqtts-broker.example.com
